name: Simulate events (daily)

on:
  schedule:
    - cron: 10 23 * * *

jobs:
  simulate_events:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Simulate VideoLearningEvents
      run: |
        python simulate-video-learning-events.py

    - name: GitHub Actor
      env: 
        GITHUB_ACTOR: ${{ github.actor }}   
      run: echo "$GITHUB_ACTOR"

    - name: GitHub Triggering Actor
      env: 
        GITHUB_TRIGGERING_ACTOR: ${{ github.triggering_actor }}   
      run: echo "$GITHUB_TRIGGERING_ACTOR"

    - name: Git Config
      run: |
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com

    - name: Git Commit
      run: |
        git add **/*.csv
        git commit -m 'chore(ml): simulate events' --allow-empty
    
    - name: Git Pull
      run: |
        git fetch
        git pull

    - name: Git Push
      run: |
        git push
